version: '3.8'
services:
  node_app:
    build:
    # you are building from where it goes to dockerfile
      context: .
      target: production
    environment:
      - NODE_ENV=production
    command: npm start