server {

    listen 80;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Nginx-Proxy true;

        proxy_pass http://node_app:4000;
        proxy_redirect off;
    }
}
# we dont have nginx in our machine but we have it in the container so what left is to use volume to copy the configuration file from our machine to the container and we can do that by adding the following lines to the docker-compose.yml file under the nginx service.

